### ISSUE TITLE
getData only loads the last part of the file

### ISSUE THREAD

**Issue by pgainullin** [theRookieCoder/drive_helper#1]
Current code seems to overwrite the output collector with the last event in the stream. I fixed it locally in my project with this:

```
  Future<String?> getData(String fileID) async {
    final file = await driveHelper.driveAPI.files.get(
      fileID,
      downloadOptions: DownloadOptions.fullMedia,
    ) as Media;
    **String fileData = '';**
    await file.stream.listen((event) {
      **fileData += String.fromCharCodes(event);**
    }).asFuture();
    return fileData;
  }
```

happy to do a PR, but haven't really tested it yet

**Comment by theRookieCoder** [comment]
Thank you for pointing this out. I don't actually use this method anywhere so I hope you will have time to test this. Let me know if this works then I'll commit and publish the new version.

**Comment by theRookieCoder** [comment]
OK, I fixed this and other changes are in the changelog

**Comment by pgainullin** [comment]
nice one, thanks
