### ISSUE TITLE
Tick drive permission by default, omit openid permission?

### ISSUE THREAD

**Issue by danielnordh** [theRookieCoder/drive_helper#3]
### Is there a way of defaulting to the Drive permission being selected?

When I set the scope to `.appData` it shows up when the user signs in, but it is not ticked by default.

<img width="552" alt="image" src="https://user-images.githubusercontent.com/3393669/214916857-2b218b46-8d9a-4fae-ba88-86aadd6dab76.png">

### Secondly, is it possible to not include openid permissions?

I'm not sure what the first line in the permissions is for.
When I look up the docs it seems to correspond to `openid`, which I'm not sure I need.
I am only interested in the user's name and email (and being able to store app data). 

Before using drive_helper, I used `GoogleSignIn(scopes: ['email', 'profile'])`

Users are much happier, and likely to sign in, when we are only asking for the permissions we actually need.
Thank you for making this helpful package!

**Comment by danielnordh** [comment]
I figured out for the second question that I can pass in an arbitrary permissions array in the init:

```dart
driveHelper.signInAndInit([
        'email',
        'profile',
        'https://www.googleapis.com/auth/drive.appdata'
      ]);
```

Unfortunately this still shows the openid row, so I guess it is baked into the appdata one.

**Comment by danielnordh** [comment]
Regarding the drive permission not being ticked by default, it has nothing to do with this package so I will close the issue.
Just a bad oversight on Google's part IMO.

**Comment by theRookieCoder** [comment]
> Just a bad oversight

I'm pretty sure it's a security feature to encourage users to read the permission properly, and not just click through the defaults.

**Comment by theRookieCoder** [comment]
> Secondly, is it possible to not include openid permissions?

I honestly don't even remember much about this project. I am planning to update it and its dependencies once Dart 3 comes out, so I'll take a look into this then.

**Comment by danielnordh** [comment]
Thanks. I ended up reverting back to google_signin for main sign in, and then only using drive helper when I'm actually doing drive stuff.

**Comment by theRookieCoder** [comment]
Not sure if you've noticed but I ended up updating it. It has some breaking changes but the API is much more ergonomic now.
